### ISSUE TITLE
showcase page is needed

### ISSUE THREAD

**Issue by mesutevin** [ceremcem/aktos-website#8]
http://www.google.com.tr/imgres?imgurl=http://www.andysowards.com/blog/assets/Noire_UI_Kit_web-user-interface.jpeg%253Fb91b38&imgrefurl=http://www.andysowards.com/blog/2012/40-best-web-ui-interface-framework-kits/&h=440&w=640&tbnid=0AHCcptVmXoRXM:&docid=J4HN0IpHm-f68M&ei=e9XpVbjHCOP9yQOj_oegCw&tbm=isch

**Comment by ceremcem** [comment]
should be look like this: http://www.prepbootstrap.com/bootstrap-theme/dark-admin/preview/index.html

**Comment by ceremcem** [comment]
Enough number of widgets added to the demo page... Consider closing this issue.

**Comment by mesutevin** [comment]
https://aktos-elektronik.com/test/#demos
